title: FiberSim
description: Spatially explicit modeling of half-sarcomeres
remote-theme: just-the-docs/just-the-docs
math: mathjax
url: https://campbell-muscle-lab.github.io/FiberSim

aux_links:
  FiberSim repo: https://github.com/Campbell-Muscle-Lab/FiberSim
  Campbell lab: http://www.campbellmusclelab.org/
